# kubeadm-config.yaml
kind: ClusterConfiguration
controlPlaneEndpoint: "k8s-rp.local:6443"
clusterName: picta-plane
apiVersion: kubeadm.k8s.io/v1beta4
kubernetesVersion: v1.34.1
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
